import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { importSlicerConfig } from '../../../src/engine/pa/slicerImport'

const fixturesDir = join(__dirname, '../../fixtures/slicer')
function readFixture(name: string): string {
  return readFileSync(join(fixturesDir, name), 'utf8')
}

const prusaFlat = `# generated by PrusaSlicer 2.7.4 on 2026-01-01 at 12:00:00 UTC
bed_shape = 5x5,305x5,305x305,5x305
nozzle_diameter = 0.4
filament_diameter = 1.75
first_layer_temperature = 215
temperature = 210
first_layer_bed_temperature = 65
bed_temperature = 60
layer_height = 0.2
first_layer_height = 75%
retract_length = 0.8
retract_speed = 35
travel_speed = 180
default_acceleration = 0
machine_max_acceleration_extruding = 1500,960
machine_max_acceleration_x = 4000,960
machine_max_jerk_x = 8,8
start_gcode = G28 ; home all\\nG90\\nM83
end_gcode = M104 S0\\nM84
filament_type = PETG
gcode_flavor = klipper
`

const prusaBundle = `# generated by PrusaSlicer 2.7.4
[print:*common*]
layer_height = 0.25
travel_speed = 120

[print:0.20mm QUALITY]
layer_height = 0.2
travel_speed = 150
default_acceleration = 1250

[filament:Prusament PLA]
filament_type = PLA
temperature = 215
first_layer_temperature = 220
filament_diameter = 1.75
bed_temperature = 60

[printer:Original Prusa MK4]
bed_shape = 0x0,250x0,250x210,0x210
nozzle_diameter = 0.4
gcode_flavor = marlin2
machine_max_jerk_x = 8
machine_max_acceleration_extruding = 4000
retract_length = 0.7
retract_speed = 40
start_gcode = G28\\nG1 Z5
end_gcode = M84

[presets]
print = 0.20mm QUALITY
filament = Prusament PLA
printer = Original Prusa MK4
`

const orcaMachine = JSON.stringify({
  type: 'machine',
  name: 'My Voron 0.4 nozzle',
  from: 'user',
  version: '1.9.0.0',
  printable_area: ['0x0', '350x0', '350x350', '0x350'],
  nozzle_diameter: ['0.4'],
  gcode_flavor: 'klipper',
  retraction_length: ['0.5'],
  retraction_speed: ['40'],
  machine_max_acceleration_extruding: ['7000', '7000'],
  machine_max_jerk_x: ['9', '9'],
  machine_start_gcode: 'PRINT_START\nG28',
  machine_end_gcode: 'PRINT_END',
  machine_pause_gcode: 'PAUSE',
})

const orcaFilament = JSON.stringify({
  type: 'filament',
  name: 'PLA Basic @Voron',
  from: 'user',
  inherits: 'fdm_filament_pla',
  filament_diameter: ['1.75'],
  nozzle_temperature: ['220'],
  nozzle_temperature_initial_layer: ['215'],
  cool_plate_temp: ['0'],
  cool_plate_temp_initial_layer: ['0'],
  hot_plate_temp: ['60'],
  hot_plate_temp_initial_layer: ['65'],
  textured_plate_temp: ['55'],
  chamber_temperatures: ['0'],
  filament_type: ['PLA'],
  filament_retraction_length: ['nil'],
  filament_retraction_speed: ['nil'],
})

describe('importSlicerConfig with a flat PrusaSlicer export', () => {
  const result = importSlicerConfig('config.ini', prusaFlat)

  it('reads the bed size from the bed_shape polygon bounding box', () => {
    expect(result.fields.printer.bedWidthMm).toBe(300)
    expect(result.fields.printer.bedDepthMm).toBe(300)
  })

  it('takes index 0 of per-extruder comma lists', () => {
    expect(result.fields.printer.nozzleDiameterMm).toBe(0.4)
    expect(result.fields.printer.retractMm).toBe(0.8)
    expect(result.fields.printer.retractSpeedMmS).toBe(35)
  })

  it('prefers first-layer temperatures', () => {
    expect(result.fields.filament.nozzleTempC).toBe(215)
    expect(result.fields.filament.bedTempC).toBe(65)
  })

  it('reads the plain scalar keys', () => {
    expect(result.fields.filament.filamentDiameterMm).toBe(1.75)
    expect(result.fields.printer.layerHeightMm).toBe(0.2)
    expect(result.fields.printer.travelSpeedMmS).toBe(180)
    expect(result.fields.filament.filamentType).toBe('PETG')
  })

  it('falls back to machine_max_acceleration_extruding when default_acceleration is 0, taking the normal value of a dual pair', () => {
    expect(result.fields.printer.printAccelMmS2).toBe(1500)
  })

  it('maps machine_max_jerk_x to square corner velocity', () => {
    expect(result.fields.printer.squareCornerVelocityMmS).toBe(8)
  })

  it('unescapes literal backslash-n in gcode', () => {
    expect(result.fields.printer.startGcode).toBe('G28 ; home all\nG90\nM83')
    expect(result.fields.printer.endGcode).toBe('M104 S0\nM84')
  })

  it('maps klipper gcode_flavor to Klipper firmware', () => {
    expect(result.fields.printer.firmware).toBe('Klipper')
  })

  it('reports imported and missing field lists', () => {
    expect(result.imported).toContain('bedWidthMm')
    expect(result.imported).toContain('startGcode')
    expect(result.imported).not.toContain('pauseGcode')
    expect(result.missing).toContain('pauseGcode')
    expect(result.missing).toContain('chamberTempC')
    expect(result.missing).not.toContain('bedTempC')
    expect(result.warnings).toEqual([])
  })
})

describe('importSlicerConfig Prusa edge cases', () => {
  it('skips percent values with a warning', () => {
    const result = importSlicerConfig('config.ini', 'layer_height = 75%\ntravel_speed = 150\n')
    expect(result.fields.printer.layerHeightMm).toBeUndefined()
    expect(result.missing).toContain('layerHeightMm')
    expect(result.warnings.some((w) => w.includes('75%'))).toBe(true)
    expect(result.fields.printer.travelSpeedMmS).toBe(150)
  })

  it('warns on an unknown gcode_flavor and leaves firmware unset', () => {
    const result = importSlicerConfig('config.ini', 'gcode_flavor = sailfish\n')
    expect(result.fields.printer.firmware).toBeUndefined()
    expect(result.missing).toContain('firmware')
    expect(result.warnings.some((w) => w.includes('sailfish'))).toBe(true)
  })

  it('falls back to non-first-layer temperatures', () => {
    const result = importSlicerConfig('config.ini', 'temperature = 240\nbed_temperature = 85\n')
    expect(result.fields.filament.nozzleTempC).toBe(240)
    expect(result.fields.filament.bedTempC).toBe(85)
  })

  it('uses default_acceleration when it is nonzero', () => {
    const result = importSlicerConfig(
      'config.ini',
      'default_acceleration = 2000\nmachine_max_acceleration_extruding = 7000\n',
    )
    expect(result.fields.printer.printAccelMmS2).toBe(2000)
  })
})

describe('importSlicerConfig with a PrusaSlicer bundle', () => {
  const result = importSlicerConfig('bundle.ini', prusaBundle)

  it('uses the presets named in [presets], not hidden *common* presets', () => {
    expect(result.fields.printer.layerHeightMm).toBe(0.2)
    expect(result.fields.printer.travelSpeedMmS).toBe(150)
  })

  it('merges printer, filament, and print sections', () => {
    expect(result.fields.printer.bedWidthMm).toBe(250)
    expect(result.fields.printer.bedDepthMm).toBe(210)
    expect(result.fields.filament.nozzleTempC).toBe(220)
    expect(result.fields.filament.filamentType).toBe('PLA')
    expect(result.fields.printer.retractMm).toBe(0.7)
    expect(result.fields.printer.printAccelMmS2).toBe(1250)
    expect(result.fields.printer.startGcode).toBe('G28\nG1 Z5')
  })

  it('maps marlin2 to Marlin', () => {
    expect(result.fields.printer.firmware).toBe('Marlin')
  })

  it('lists one named filament per non-hidden [filament:...] section', () => {
    const twoFilaments =
      prusaBundle +
      '\n[filament:*template*]\nfilament_type = TPU\n' +
      '\n[filament:Extrudr PETG]\nfilament_type = PETG\ntemperature = 240\nfirst_layer_bed_temperature = 85\nfilament_diameter = 1.75\n'
    const r = importSlicerConfig('bundle.ini', twoFilaments)
    expect(r.filaments.map((f) => f.name)).toEqual(['Prusament PLA', 'Extrudr PETG'])
    expect(r.filaments[0].fields.nozzleTempC).toBe(220)
    expect(r.filaments[0].fields.filamentType).toBe('PLA')
    expect(r.filaments[1].fields.nozzleTempC).toBe(240)
    expect(r.filaments[1].fields.bedTempC).toBe(85)
    expect(r.filaments[1].fields.filamentType).toBe('PETG')
  })

  it('reports no bundle filaments for a flat export', () => {
    const r = importSlicerConfig('config.ini', prusaFlat)
    expect(r.filaments).toEqual([])
  })

  it('falls back to the first non-hidden preset per section when [presets] is absent', () => {
    const noPresets = prusaBundle.replace(/\[presets\][\s\S]*$/, '')
    const r = importSlicerConfig('bundle.ini', noPresets)
    expect(r.fields.printer.layerHeightMm).toBe(0.2)
    expect(r.fields.printer.bedWidthMm).toBe(250)
  })
})

describe('importSlicerConfig with an OrcaSlicer machine preset', () => {
  const result = importSlicerConfig('My Voron 0.4 nozzle.json', orcaMachine)

  it('reads the bed size from the printable_area polygon', () => {
    expect(result.fields.printer.bedWidthMm).toBe(350)
    expect(result.fields.printer.bedDepthMm).toBe(350)
  })

  it('takes element 0 of string arrays', () => {
    expect(result.fields.printer.nozzleDiameterMm).toBe(0.4)
    expect(result.fields.printer.retractMm).toBe(0.5)
    expect(result.fields.printer.retractSpeedMmS).toBe(40)
    expect(result.fields.printer.printAccelMmS2).toBe(7000)
    expect(result.fields.printer.squareCornerVelocityMmS).toBe(9)
  })

  it('reads machine gcode with real newlines and the pause gcode', () => {
    expect(result.fields.printer.startGcode).toBe('PRINT_START\nG28')
    expect(result.fields.printer.endGcode).toBe('PRINT_END')
    expect(result.fields.printer.pauseGcode).toBe('PAUSE')
  })

  it('maps the firmware and reports filament fields as missing', () => {
    expect(result.fields.printer.firmware).toBe('Klipper')
    expect(result.missing).toContain('filamentDiameterMm')
    expect(result.missing).toContain('nozzleTempC')
    expect(result.missing).toContain('filamentType')
    expect(result.warnings).toEqual([])
  })
})

describe('importSlicerConfig with an OrcaSlicer filament preset', () => {
  const result = importSlicerConfig('PLA Basic.json', orcaFilament)

  it('prefers the initial-layer nozzle temperature', () => {
    expect(result.fields.filament.nozzleTempC).toBe(215)
  })

  it('prefers the hot plate initial-layer temperature for the bed', () => {
    expect(result.fields.filament.bedTempC).toBe(65)
  })

  it('reads chamber temperature, filament type, and diameter', () => {
    expect(result.fields.filament.chamberTempC).toBe(0)
    expect(result.fields.filament.filamentType).toBe('PLA')
    expect(result.fields.filament.filamentDiameterMm).toBe(1.75)
  })

  it('treats "nil" entries as absent', () => {
    expect(result.fields.printer.retractMm).toBeUndefined()
    expect(result.missing).toContain('retractMm')
  })

  it('warns about inheritance because the preset carries inherits', () => {
    expect(result.warnings.some((w) => w.toLowerCase().includes('inherit'))).toBe(true)
  })
})

describe('importSlicerConfig with a sparse Orca preset that inherits', () => {
  it('imports what is present and warns about the system parent', () => {
    const sparse = JSON.stringify({
      type: 'process',
      name: '0.20mm mine',
      inherits: '0.20mm Standard @BBL X1C',
      layer_height: '0.2',
    })
    const result = importSlicerConfig('process.json', sparse)
    expect(result.fields.printer.layerHeightMm).toBe(0.2)
    expect(result.imported).toEqual(['layerHeightMm'])
    expect(result.warnings.some((w) => w.toLowerCase().includes('inherit'))).toBe(true)
  })
})

describe('importSlicerConfig with unusable content', () => {
  it('throws a user-worded error on content that is neither JSON nor INI-like', () => {
    expect(() => importSlicerConfig('photo.txt', 'PK not a config at all')).toThrow(
      /does not look like/i,
    )
  })
})


describe('importSlicerConfig with real-world fixtures', () => {
  describe('a real PrusaSlicer printer .ini (prusa_printer_tridentbert.ini)', () => {
    const content = readFixture('prusa_printer_tridentbert.ini')
    const result = importSlicerConfig('prusa_printer_tridentbert.ini', content)

    it('reads the bed size from bed_shape = 0x0,300x0,300x300,0x300', () => {
      expect(result.fields.printer.bedWidthMm).toBe(300)
      expect(result.fields.printer.bedDepthMm).toBe(300)
    })

    it('reads nozzle diameter, retraction, and jerk', () => {
      expect(result.fields.printer.nozzleDiameterMm).toBe(0.4)
      expect(result.fields.printer.retractMm).toBe(0.75)
      expect(result.fields.printer.retractSpeedMmS).toBe(50)
      expect(result.fields.printer.squareCornerVelocityMmS).toBe(10)
    })

    it('falls back to machine_max_acceleration_extruding since default_acceleration is absent', () => {
      expect(result.fields.printer.printAccelMmS2).toBe(1500)
    })

    it('maps the klipper gcode_flavor to Klipper firmware', () => {
      expect(result.fields.printer.firmware).toBe('Klipper')
    })

    it('reads the end gcode containing the print_end macro call', () => {
      expect(result.fields.printer.endGcode).toContain('print_end')
    })

    it('reads the pause_print_gcode', () => {
      expect(result.fields.printer.pauseGcode).toBe('M601')
    })

    it('reports fields this printer-only ini cannot fill as missing, consistent with imported', () => {
      expect(result.missing).toContain('filamentDiameterMm')
      expect(result.missing).toContain('nozzleTempC')
      expect(result.missing).toContain('bedTempC')
      expect(result.missing).toContain('layerHeightMm')
      expect(result.missing).toContain('travelSpeedMmS')
      expect(result.missing).toContain('filamentType')
      expect(result.missing).toContain('chamberTempC')
      for (const field of result.missing) expect(result.imported).not.toContain(field)
      for (const field of result.imported) expect(result.missing).not.toContain(field)
    })
  })

  describe('a real OrcaSlicer machine preset with no "type" field (orca_machine_tridentbert.json)', () => {
    const content = readFixture('orca_machine_tridentbert.json')
    const result = importSlicerConfig('orca_machine_tridentbert.json', content)

    it('is still recognized as an Orca preset via printer_settings_id, not "type"', () => {
      expect(result.fields.printer.bedWidthMm).toBeDefined()
    })

    it('reads the bed size from printable_area 0x0,300x0,300x240,0x240', () => {
      expect(result.fields.printer.bedWidthMm).toBe(300)
      expect(result.fields.printer.bedDepthMm).toBe(240)
    })

    it('reads retraction_length and takes element 0 of the dual acceleration/jerk arrays', () => {
      expect(result.fields.printer.retractMm).toBe(0.6)
      expect(result.fields.printer.printAccelMmS2).toBe(45000)
      expect(result.fields.printer.squareCornerVelocityMmS).toBe(40)
    })

    it('reads the machine_start_gcode', () => {
      expect(result.fields.printer.startGcode).toContain('PRINT_START')
    })

    it('falls back to change_filament_gcode for the pause gcode', () => {
      expect(result.fields.printer.pauseGcode).toBe('PAUSE')
    })

    it('warns about the "Voron Trident 300 0.4 nozzle" inherits parent', () => {
      expect(result.warnings.some((w) => w.toLowerCase().includes('inherit'))).toBe(true)
    })

    it('reports imported and missing lists that are consistent (no field in both)', () => {
      expect(result.missing).toContain('nozzleDiameterMm')
      expect(result.missing).toContain('firmware')
      for (const field of result.imported) expect(result.missing).not.toContain(field)
      for (const field of result.missing) expect(result.imported).not.toContain(field)
    })
  })

  describe('a real OrcaSlicer filament preset for PLA (orca_filament_extruder_pla.json)', () => {
    const content = readFixture('orca_filament_extruder_pla.json')
    const result = importSlicerConfig('orca_filament_extruder_pla.json', content)

    it('reads the hot_plate_temp_initial_layer as bed temperature', () => {
      expect(result.fields.filament.bedTempC).toBe(60)
    })

    it('has no nozzle_temperature key in this preset, so nozzleTempC is missing', () => {
      expect(result.fields.filament.nozzleTempC).toBeUndefined()
      expect(result.missing).toContain('nozzleTempC')
    })

    it('warns about the "Generic PLA @System" inherits parent', () => {
      expect(result.warnings.some((w) => w.toLowerCase().includes('inherit'))).toBe(true)
    })

    it('reports imported and missing lists that are consistent', () => {
      for (const field of result.imported) expect(result.missing).not.toContain(field)
      for (const field of result.missing) expect(result.imported).not.toContain(field)
    })
  })

  describe('a real OrcaSlicer filament preset for PETG (orca_filament_elegoo_petg.json)', () => {
    const content = readFixture('orca_filament_elegoo_petg.json')
    const result = importSlicerConfig('orca_filament_elegoo_petg.json', content)

    it('prefers nozzle_temperature_initial_layer for nozzle temperature', () => {
      expect(result.fields.filament.nozzleTempC).toBe(260)
    })

    it('has no hot_plate_temp key in this preset, so bedTempC is missing', () => {
      expect(result.fields.filament.bedTempC).toBeUndefined()
      expect(result.missing).toContain('bedTempC')
    })

    it('warns about the "Generic PETG @System" inherits parent', () => {
      expect(result.warnings.some((w) => w.toLowerCase().includes('inherit'))).toBe(true)
    })

    it('reports imported and missing lists that are consistent', () => {
      for (const field of result.imported) expect(result.missing).not.toContain(field)
      for (const field of result.missing) expect(result.imported).not.toContain(field)
    })
  })

  describe('a real OrcaSlicer tool-changer machine preset with no "type" field (orca_machine_chubechanger.json)', () => {
    const content = readFixture('orca_machine_chubechanger.json')
    const result = importSlicerConfig('orca_machine_chubechanger.json', content)

    it('is recognized as an Orca preset via printer_settings_id', () => {
      expect(result.fields.printer.nozzleDiameterMm).toBeDefined()
    })

    it('reads nozzle diameter and retraction from the dual-extruder arrays (element 0)', () => {
      expect(result.fields.printer.nozzleDiameterMm).toBe(0.4)
      expect(result.fields.printer.retractMm).toBe(0.8)
      expect(result.fields.printer.retractSpeedMmS).toBe(30)
    })

    it('reads the machine_start_gcode', () => {
      expect(result.fields.printer.startGcode).toContain('PRINT_START')
    })

    it('warns about the "Voron 2.4 300 0.4 nozzle" inherits parent', () => {
      expect(result.warnings.some((w) => w.toLowerCase().includes('inherit'))).toBe(true)
    })

    it('has no printable_area key in this preset, so bed size is missing', () => {
      expect(result.fields.printer.bedWidthMm).toBeUndefined()
      expect(result.fields.printer.bedDepthMm).toBeUndefined()
      expect(result.missing).toContain('bedWidthMm')
      expect(result.missing).toContain('bedDepthMm')
    })

    it('reports imported and missing lists that are consistent', () => {
      for (const field of result.imported) expect(result.missing).not.toContain(field)
      for (const field of result.missing) expect(result.imported).not.toContain(field)
    })
  })
})
